from modules import query
import time

def default_queries(driver):
    report_data = {}
    report_data['domains'] = query.get_domains(driver)
    report_data['dcs'] = query.get_DCs(driver)
    report_data['computers'] = query.get_computers(driver)
    report_data['sessions'] = query.get_sessionCount(driver)
    report_data['users'] = query.get_users(driver)
    report_data['enabled_users'] = query.get_Enabledusers(driver)
    report_data['owned_users'] = query.get_ownedUsersCount(driver)
    query.get_ownedUsers(driver)
    query.get_daSessions(driver)
    query.get_sessions(driver)
    query.get_certTempNotAdmin(driver)
    query.get_certEnroll(driver)
    query.get_userDesc(driver)
    query.get_compDesc(driver)
    query.get_adminUsers(driver)
    query.get_adminGroups(driver)
    query.get_localAdmins(driver)
    query.get_groupDesc(driver)
    query.get_compSPNs(driver)
    query.get_dcsync(driver)
    query.get_kerbUsers(driver)
    query.get_asprepRoast(driver)
    query.get_unconstrainedDel(driver)
    query.get_compOwners(driver)
    query.get_serverRDP(driver)
    query.get_serverAdminGroup(driver)
    query.get_pwdYear(driver)
    query.get_userNoLogon(driver)
    query.get_computersNoLAPS(driver)
    query.get_oldComps(driver)
    #query.get_firstDegreeUserDCOM(driver) # NEED TO MOVE TO DCOM MODULE
    #query.get_groupDelUserDCOM(driver)
    #query.get_firstDegreeGroupDCOM(driver)
    query.get_passNeverExpire(driver)
    query.get_disabledOutboundRights_firstDegree(driver)
    query.get_passNotRequired(driver)
    query.get_allowedToAct(driver)
    query.get_writeAccountRestrictions(driver)
    return report_data
