[bloodhound]
URI = "neo4j://localhost:7687"
USERNAME = "neo4j"
PASSWORD = "password"
DATABASE = "neo4j"
OUTPUT_DIR = "output"

[example]
URI = "neo4j://localhost:7687"
USERNAME = "neo4j"
PASSWORD = "password"
DATABASE = "neo4j"
OUTPUT_DIR = "output"
